server:
  port: 8090

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher  # swagger2 문서 오류 때문에

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/musical?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root1234!

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100


logging:
  level:
    org.hibernate.SQL: info


jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-mils: 3600000   # 1 hour
